COLUMNS:
  brand: list
  bullet_point: list
  color: list
  item_id: str
  item_name: list
  model_name: list
  model_number: list
  model_year: list
  product_type: list
  style: list
  main_image_id: str
  item_keywords: list
  country: str
  marketplace: str
  domain_name: str


TARGET_COLUMN:
  name: complete_product_description