artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?export=download&id=1NNqlat1GdreoGhMTC5G8l5Q7XV-qtfVp
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  listings_path: "artifacts/data_ingestion/data/listings_*.json"
  images_path: "artifacts/data_ingestion/data/images.csv"
  STATUS_FILE: artifacts/data_transformation/status.txt
  data_csv_path: "artifacts/data_transformation/df_data.csv"


data_validation:
  root_dir: artifacts/data_validation
  data_path: "artifacts/data_transformation/df_data.csv"
  images_path: "artifacts/data_ingestion/data/images.csv"
  data_master_path: "artifacts/data_validation/df_master.csv"
  data_sample_path: "artifacts/data_validation/df_sample_20k.csv"
  STATUS_FILE: artifacts/data_validation/status.txt
  image_path_prefix: "artifacts/data_ingestion/data/small/images/small/"
  #image_path_prefix: "/Users/mitilroy/IK/Projects/Capstone/ShopTalk/abo-images-small/images/small/" ##No need for this anymore


data_visualization:
  root_dir: artifacts/data_visualization
  data_master_path: "artifacts/data_validation/df_master.csv"
  data_sample_path: "artifacts/data_validation/df_sample_20k.csv"


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: "artifacts/data_validation/df_sample_20k.csv"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: "artifacts/data_validation/df_sample_20k.csv"
  model_path: fine_tuned_lora_tripletloss
  metric_file_name: artifacts/model_evaluation/metrics.json