artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  #source_URL: https://github.com/someshnaman/End_to_end_MLOPS_project_/raw/master/wine-data.zip
  source_URL: https://drive.google.com/uc?export=download&id=1NNqlat1GdreoGhMTC5G8l5Q7XV-qtfVp
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  listings_path: "artifacts/data_ingestion/data/listings_*.json"
  images_path: "artifacts/data_ingestion/data/images.csv"
  STATUS_FILE: artifacts/data_transformation/status.txt
  data_csv_path: "artifacts/data_transformation/df_data.csv"


data_validation:
  root_dir: artifacts/data_validation
  data_path: "artifacts/data_transformation/df_data.csv"
  images_path: "artifacts/data_ingestion/data/images.csv"
  data_master_path: "artifacts/data_validation/df_master.csv"
  data_sample_path: "artifacts/data_validation/df_sample_20k.csv"
  STATUS_FILE: artifacts/data_validation/status.txt


data_visualization:
  root_dir: artifacts/data_visualization
  data_master_path: "artifacts/data_validation/df_master.csv"
  data_sample_path: "artifacts/data_validation/df_sample_20k.csv"


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json